name: northwind

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    user: postgres:postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ALLOW_IP_RANGE: "0.0.0.0/0"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d northwind" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgdata:/var/lib/postgresql/data
    networks:
      - db

volumes:
  pgdata:
    name: northwind-pgdata
    driver_opts:
      type: "none"
      o: "bind"
      device: ${DATA_PATH_HOST}/postgres/northwind
  pgadmin-data:
    name: pgadmin-data
    driver_opts:
      type: "none"
      o: "bind"
      device: ${DATA_PATH_HOST}/pgadmin


networks:
  db:
    driver: bridge
    
